### ISSUE TITLE
Watch memory and restart workers

### ISSUE THREAD

**Issue by kelunik** [amphp/http-server#135]
Workers should be watched and restarted before they exhaust the current memory limit instead of crashing once it happens. A message should be logged, so the user knows there's a memory leak.

**Comment by bwoebi** [comment]
How exactly are you thinking this shall be implemented?

Having an Option with like memoryUsageStop … and if memory_get_usage() > memoryUsageStop, then $logger->warn("..."); gc_collect_cycles() … if still higher: $worker->stop(); in a repeat watcher of one second?

**Comment by kelunik** [comment]
Something like that, yes.

**Comment by rybakit** [comment]
I'm curious if this feature can be ported to [amphp/parallel](https://github.com/amphp/parallel)?

**Comment by kelunik** [comment]
@rybakit Just open an issue there if you want that.

**Comment by kelunik** [comment]
I think we should add this in form of a soft memory limit option.

**Comment by kelunik** [comment]
This won't be implemented here. A solution might be implemented in `amphp/parallel` that can be taken advantage of then. Worker management is no longer part of `amphp/http-server`.
