### ISSUE TITLE
Fault tolerant body parsing

### ISSUE THREAD

**Issue by brstgt** [amphp/http-server#180]
The body parser is pretty strict. During the migration from FPM to Aerys I encountered bogus requests that have been parsed by FPM without complaints but Aerys created undesired results.

Probably Aerys was correct in terms of RFCs but this did not help the migration.
I implemented a middleware to fix the requests.

Is there a policy how to treat things like that? E.g.
- Keep aerys as strict + clean as possible
- Bundle middlewares as optional BC helpers in aerys
- Offer separate packages with helpers
- Offer a non-strict mode in BodyParser

**Comment by kelunik** [comment]
Do you have some examples that FPM parses, but where Aerys errors out?

**Comment by brstgt** [comment]
I know, this is really sick, but this is the example:

content-type-header = "multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449,multipart/form-data; boundary=---------------------------14737809831466499882746641449"

body = "\r\n-----------------------------14737809831466499882746641449\r\nContent-Disposition: form-data; name=\"foo\"\r\n\r\nFoobar\r\n-----------------------------14737809831466499882746641449\r\nContent-Disposition: form-data; name=\"bar\"\r\n\r\nFoobar\n-----------------------------14737809831466499882746641449--\r\n"

**Comment by kelunik** [comment]
Relevant RFC: https://tools.ietf.org/html/rfc2045#section-5.1

**Comment by kelunik** [comment]
We could split the header for each `,` (reverse header combination) and parse it like it would be sent as that:

```
content-type: multipart/form-data; boundary=---------------------------14737809831466499882746641449
content-type: multipart/form-data; boundary=---------------------------14737809831466499882746641449
content-type: multipart/form-data; boundary=---------------------------14737809831466499882746641449
...
```

If all boundaries are exactly the same, we could probably accept that.

**Comment by brstgt** [comment]
I think aerys is actually not really RFC conform in this case. Header param values must either be quoted or may not contain ctl characters

```
     value := token / quoted-string

     token := 1*<any (US-ASCII) CHAR except SPACE, CTLs,
                 or tspecials>

     tspecials :=  "(" / ")" / "<" / ">" / "@" /
                   "," / ";" / ":" / "\" / <">
                   "/" / "[" / "]" / "?" / "="
                   ; Must be in quoted-string,
                   ; to use within parameter values
```

**Comment by kelunik** [comment]
That's correct. Parsing it correctly probably solves it, too, because it should just ignore all further parameters then.

https://github.com/amphp/aerys/blob/847a000026f1f03ffc093e1375fd562b3fe1ecbb/lib/BodyParser.php#L65

**Comment by bwoebi** [comment]
https://github.com/amphp/aerys/blob/847a000026f1f03ffc093e1375fd562b3fe1ecbb/lib/BodyParser.php#L65

Aerys actually supports the optional "" quotes. It however does not reject incorrect strings (i.e. where it isn't quoted.

Also, I find nothing in the RFC permitting comma separation at all?

**Comment by kelunik** [comment]
@bwoebi Comma separation is the usual way of combining multiple headers with the same name, but it's only allowed if the header value is a list of tokens.

**Comment by bwoebi** [comment]
@kelunik Exactly, and the content-type is not defined as a list of tokens as per https://tools.ietf.org/html/rfc7231#section-3.1.1.5

**Comment by kelunik** [comment]
@brstgt Which tool generated these requests again?

**Comment by kelunik** [comment]
I'm closing this issue, as body parsing is no longer part of this repository, but instead moved to https://github.com/amphp/http-server-form-parser.

@brstgt Please open an issue there if the problem still persists and mention the name of the tool that generated the request.
