### ISSUE TITLE
Improved worker + watcher management

### ISSUE THREAD

**Issue by brstgt** [amphp/http-server#181]
The watcher process already has a commnunication channel to each worker, the IPC socket. This socket is currently pretty dumb.
I think this could be easily extended to share more information between worker + watcher.

Examples:
- Measure number of executed requests
- Measure worker utilization (https://github.com/amphp/amp/issues/161)
- Detect unresponsive workers (too long running requests, dead locks, whatever)

The IPC protocol could be command based and bidirectional. E.g.
```
4 byte cmd length:cmd string:4 byte data length:data
```
Commands from watcher to worker could be
- stop
- heartbeat (passive)
- stats

Commands from worker to watcher could be
- log
- heartbeat (active)

Another option would be to use a HTTP2 connection between worker and watcher. That would be even more consistent with the Aerys architecture.

Having all that a HTTP based management interface for the watcher would make sense to issue commands to the watcher like:
- Restart
- Gather stats (Utilization, Number of workers, ...)
- Change worker count
- ...

Why HTTP management?
1. Aerys is HTTP
2. Distributed management is easier with HTTP than with SSH/CLI
3. Reporting API makes sense as a RESTful service

**Comment by kelunik** [comment]
I think most of these don't have to go to the master to be submitted to some time series database. You could send the metrics for each worker directly to the TSD.

Completely unresponsive worker detection should probably be built-in directly.

Anyway, the IPC communication probably needs a redesign.

**Comment by kelunik** [comment]
We have recently discussed dropping the current approach entirely and providing the process manager as extra package.

**Comment by kelunik** [comment]
@brstgt We have built a HTTP-independent solution in https://github.com/amphp/cluster. Could you review the API and share your thoughts? Should we allow completely user-defined IPC? Is it enough to have built-in logging and heartbeats?

**Comment by kelunik** [comment]
Worker management is no longer part of `amphp/http-server`, thus I'm closing this issue. Issues should instead be opened for `amphp/cluster`.
