### ISSUE TITLE
Path encoding

### ISSUE THREAD

**Issue by kelunik** [amphp/http-server#214]
Currently `Uri::getPath()` is encoded, which leads to FastRoute arguments being encoded. If I read https://tools.ietf.org/html/rfc3986.html#section-2.4 right, we should decode directly in `Uri` and `getPath()` should return the decoded path.

**Comment by trowski** [comment]
Yes, I noticed this the other day. It definitely needs to be decoded with `urldecode()`.

**Comment by kelunik** [comment]
Rather `rawurldecode`.

**Comment by trowski** [comment]
That leaves `+` in URLs instead of spaces. I believe that's the only difference.

**Comment by trowski** [comment]
Yes, I think so. Unrelated, but just FYI IPv6 address need fixing, as passing `[::1]` results in a host of `[[::1]]`.

**Comment by kelunik** [comment]
I think the only place that might "break" (actually work correctly then) in Artax is https://github.com/amphp/artax/blob/4810ea63c0a34bf05327d41b59dcbba5f6467f67/lib/DefaultClient.php#L664.

**Comment by trowski** [comment]
Yeah, is it really a BC break when technically the result was wrong in the first place?

**Comment by kelunik** [comment]
No, I think that one is fine and can just be upgraded to the new version.

**Comment by kelunik** [comment]
Closing, because the issue moved to https://github.com/amphp/http-server-router/issues/4.
