### ISSUE TITLE
Provide a way to handle fall through / fallback requests

### ISSUE THREAD

**Issue by PeeHaa** [amphp/http-server#218]
When a request comes in which matches no handlers we can add a trailing `->use(function(){})` handler.

However there is no easy way to load a specific fallback file from the docroot.

This functionality would work basically the same as Apache's `FallbackResource` and nginx's `try_files` directives.

My current use case is that I need all non matching requests to go through my main `{docroot}/index.html` file which renders different content based on the requested URI.

**Comment by kelunik** [comment]
It's a common pattern for SPAs, I've needed that myself in the past. It's probably best to have a static file responder, that just responds with a single static file.

**Comment by trowski** [comment]
Good candidate for the package that `Root` goes into I think.

**Comment by kelunik** [comment]
Closing in favor of https://github.com/amphp/http-server-static-content/issues/2.
