### ISSUE TITLE
ServerObserver conflicts with Websocket\Application

### ISSUE THREAD

**Issue by kelunik** [amphp/http-server#222]
Their `onStart()` methods are not compatible, thus it's not possible to implement both in a single class.

**Comment by trowski** [comment]
Same issue with `onStop()`. Should we just pick different names for these?

**Comment by kelunik** [comment]
Probably, yes.

**Comment by trowski** [comment]
`onBoot()` and `onShutdown()`?

**Comment by kelunik** [comment]
Maybe we should just find another way to inject the `$endpoint`.

**Comment by trowski** [comment]
How about adding `init(Endpoint $endpoint)` that is invoked when the `Application` is given to the responder and remove `onStart()` and `onStop()` from `Application`, allowing the user to implement `ServerObserver` if they care about those events.

Alternatively, `Websocket` could be an abstract class (with mostly final methods) that must be extended. That class could also act as the endpoint, removing the need to inject anything.

**Comment by kelunik** [comment]
@trowski I thought about that, I'm probably in favor. Often you don't do anything in those methods anyway, at least for simpler applications where the WebSocket connection is just used for broadcasting new events, see e.g. [here](https://github.com/kelunik/amphp-arduino/commit/18b2c967bcede054caf68775d9293ece76002646#diff-73d22c60569229b683d23acd2bcb778b).

I'd also maybe build the origin check into the class, so people won't forget it.

**Comment by kelunik** [comment]
Closing in favor of https://github.com/amphp/websocket-server/issues/1.
