### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by kelunik** [amphp/http-server#226]
The 0.8.x will change a lot of things, so we need a big documentation update. How should we organize this so we don't end up doing double work and inconsistencies?

**Comment by krlv** [comment]
Maybe you can split it into separate issues (eg. update `middleware` doc; update `classes/client` doc, etc.) and then assign each issue to a contributor (or to yourself if no one volunteers 😞). 

Also, it would be great if you can give a hint what should be added/updated in each case.

**Comment by krlv** [comment]
Btw, I can try to start with `docs/classes/request.md` update, if no one is working on it.

**Comment by kelunik** [comment]
@krlv Just started yesterday with the documentation update, don't have a fixed TODO list, yet. I opened https://github.com/amphp/http-server/issues/242 and "assigned" it to you, assignment doesn't work directly to external contributors. :-(

**Comment by krlv** [comment]
I guess external contributors should leave a comment in the issue they want to work on. Saw this couple of times during Hacktoberfest.

**Comment by krlv** [comment]
@kelunik I can continue with `docs/classes/message.md` docs (if you not working on ti at the moment)

**Comment by kelunik** [comment]
@krlv Better skip that for now, because it's likely to be renamed or moved into `amphp/http`. You could work on `Response` if you want.

**Comment by krlv** [comment]
Ok, will do `Response` update then.

**Comment by krlv** [comment]
@kelunik let me know if I can help with something else.

**Comment by kelunik** [comment]
@krlv Thanks for the offer! You could look into documenting `Options` if you want. If you have even more time, you could also update the options on https://amphp.org/http-server/production#options and remove the no longer existing ones there.

**Comment by kelunik** [comment]
I think only the production options are missing now. :-)

**Comment by kelunik** [comment]
Closing, as we're complete.

**Comment by trowski** [comment]
Server still needs an update.
