### ISSUE TITLE
Add 'Testing' and 'Contributing' sections to README

### ISSUE THREAD

**Issue by krlv** [amphp/http-server#238]
It would be nice to have following sections in README.md:

## Running the tests
```
composer test
```
To get code coverage report, you can check `php-code-coverage` dashboard at ./build/coverage/index.html

## Contributing
Please read [CONTRIBUTING.md](https://github.com/amphp/amp/blob/master/CONTRIBUTING.md) for details on our code of conduct, and the process for submitting pull requests to us.

**Comment by kelunik** [comment]
Should testing be its own section or should we rather move that into `CONTRIBUTING.md`?

**Comment by krlv** [comment]
Right, make sense to move "testing" to `CONTRIBUTING.md`. Will do PR(s)

**Comment by krlv** [comment]
PR to update `CONTRIBUTING.md`: https://github.com/amphp/amp/pull/206
