### ISSUE TITLE
Type of Response::getBody()

### ISSUE THREAD

**Issue by kelunik** [amphp/http-server#244]
Should `Response::getBody()` return a `Payload` or `InputStream`?

**Comment by trowski** [comment]
`InputStream` is fine IMO since the user can wrap the return with `Payload` if desired. Most middlewares would want to stream the response body anyway to be general-purpose.

**Comment by kelunik** [comment]
@trowski Makes sense, it allows stream generators to use `finally` to abort generating data if discarded.
