### ISSUE TITLE
Uncaught OutOfBoundsException: Required package "amphp/aerys" is not installed:

### ISSUE THREAD

**Issue by kixortillan** [amphp/http-server#251]
Playing around http-server when I encountered this error

PHP Fatal error:  Uncaught OutOfBoundsException: Required package "amphp/aerys" is not installed: cannot detect its version in /home/kian/Projects/asyncphp/vendor/ocramius/package-versions/src/PackageVersions/Versions.php:46
Stack trace:
#0 /home/kian/Projects/asyncphp/vendor/amphp/http-server/lib/constants.php(6): PackageVersions\Versions::getVersion('amphp/aerys')
#1 /home/kian/Projects/asyncphp/vendor/composer/autoload_real.php(66): require('/home/kian/Proj...')
#2 /home/kian/Projects/asyncphp/vendor/composer/autoload_real.php(56): composerRequire11d6e1042cac0c3c594f8ae0df1a75f1('8487d1bf6a2183b...', '/home/kian/Proj...')
#3 /home/kian/Projects/asyncphp/vendor/autoload.php(7): ComposerAutoloaderInit11d6e1042cac0c3c594f8ae0df1a75f1::getLoader()
#4 /home/kian/Projects/asyncphp/vendor/amphp/http-server/bin/aerys(59): require('/home/kian/Proj...')
#5 /home/kian/Projects/asyncphp/vendor/amphp/http-server/bin/aerys(60): {closure}()
#6 {main}
  thrown in /home/kian/Projects/asyncphp/vendor/ocramius/package-versions/src/PackageVersions/Versions.php on line 46

I checked /lib/constants.php and it is calling this static method

const SERVER_NAME = "aerys";
define(__NAMESPACE__ . "\\SERVER_VERSION", \str_replace([".9999999", "9999999-"], "", \PackageVersions\Versions::getVersion('amphp/aerys')));

As far as I can tell. Packagist provides an outdated version of http-server (still giving aerys) as it is pointing to latest v0.7.4. Checking [v0.7.4](https://github.com/amphp/http-server/tree/v0.7.4) I confirmed that it is still using Aerys namespace and probably why constants.php is looking for amphp\aerys. Checking your master branch I can see you changed the namespace to Amp\Http\Server.

Not very familiar with packagist deployment so those are just guesses. Thanks.

**Comment by kelunik** [comment]
Seems like you're using an older version. Please use `amphp/aerys` as package name for versions before `0.8.0`. We've just released `0.8.0`, so you might want to look at that instead.
