### ISSUE TITLE
Response latency significantly increased after upgrade from v0.7.4 to v0.8.0

### ISSUE THREAD

**Issue by torinaki** [amphp/http-server#252]
Seem there is an issue with performance have been introduced in version v0.8.0 or there were some changes in default server settings.

Comparing versions v0.7.4 and v0.8.0 there are about 25%-80% of latency difference (on different tests).
* v0.7.4
```
Running 30s test @ http://localhost:8080/
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.02ms    0.98ms 126.00ms   99.59%
    Req/Sec    12.54k   278.07    13.01k    71.67%
  Latency Distribution
     50%    7.94ms
     75%    8.15ms
     90%    8.33ms
     99%    8.73ms
  374367 requests in 30.00s, 73.90MB read
Requests/sec:  12477.51
Transfer/sec:      2.46MB
```
* v0.8.0
```
Running 30s test @ http://localhost:8080/
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    40.29ms    1.69ms  51.42ms   89.09%
    Req/Sec     2.49k   175.34     2.89k    68.67%
  Latency Distribution
     50%   39.92ms
     75%   40.02ms
     90%   43.47ms
     99%   44.17ms
  74256 requests in 30.02s, 14.68MB read
Requests/sec:   2473.37
Transfer/sec:    500.62KB
```

To reproduce this issue please use [wrk](https://github.com/wg/wrk):
```bash
 wrk -t1 -c100 -d30s --latency http://localhost:8080/
```
and following server scripts:
* v0.7.4 https://github.com/torinaki/aerys-benchmark/blob/master/aerys/v0.7.4/server-tiny.php
* v0.8 https://github.com/torinaki/aerys-benchmark/blob/master/aerys/v0.8/server-tiny.php

**Comment by trowski** [comment]
The executable `bin/aerys` that used to be provided in this repo would spawn multiple processes to handle requests. That functionality has been moved to [`amphp/cluster`](https://github.com/amphp/cluster) (a work-in-progress right now, but nearly complete). Undoubtedly we'll include some examples in the future that use that package to handle requests from multiple processes. You can specify the number of workers with the `-w` flag to `bin/aerys` (i.e., `bin/aerys -w 1 -c server-tiny.php`).

In v0.8.0 only a single process handles requests by default. Using the scripts you provided and the commands shown yields the following on my laptop:

**v0.7.4:** Run using `php -dzend.assertions=-1 bin/aerys -w 1 -c server-tiny.php`
```
Running 30s test @ http://localhost:8080/
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.88ms    3.91ms 223.73ms   95.88%
    Req/Sec    14.95k     2.25k   17.63k    86.33%
  Latency Distribution
     50%    6.21ms
     75%    6.79ms
     90%    8.18ms
     99%   16.24ms
  446389 requests in 30.01s, 88.12MB read
Requests/sec:  14876.14
Transfer/sec:      2.94MB
```

**v0.8.0:** Run using `php -dzend.assertions=-1 server-tiny.php`
```
Running 30s test @ http://localhost:8080/
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.80ms    3.32ms 228.38ms   99.59%
    Req/Sec    13.02k   453.77    13.89k    75.00%
  Latency Distribution
     50%    7.56ms
     75%    7.97ms
     90%    8.42ms
     99%    9.74ms
  388722 requests in 30.01s, 76.74MB read
Requests/sec:  12954.75
Transfer/sec:      2.56MB
```

There is some performance penalty in v0.8.0, however we improved some features such as header validation and overall have better abstractions for writing response handlers or middleware, while still maintaining a very high level of performance.

**Comment by trowski** [comment]
I tried using the current master of `amphp/cluster` and v0.8.0 with a modified version of your example that uses `Cluster::listen()` instead of `Socket\listen()` to share sockets between processes and got the following results, pegging my laptop to 100% CPU during the 30s, so I'm sure better hardware would provide much better results.

```
Running 30s test @ http://localhost:8080/
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.69ms    2.86ms  36.84ms   87.19%
    Req/Sec    29.98k     2.43k   35.79k    69.33%
  Latency Distribution
     50%    2.87ms
     75%    4.36ms
     90%    7.24ms
     99%   14.64ms
  894969 requests in 30.02s, 176.68MB read
Requests/sec:  29811.63
Transfer/sec:      5.89MB
```

**Comment by torinaki** [comment]
@trowski I see your point with cluster setup, but in my comparison, I'm using only one process, because it will show how good single core utilization is (it is exactly what I want to achieve with async approach). `Aerys\initServer` function guarantees that I'm using only one process for Aerys `v0.7.4`. In case of `v0.8.0` i'm not using `amphp/cluster`. 
Also, both versions servers are running using same PHP settings.

Here is complete benchmark report on Travis:
https://travis-ci.org/torinaki/aerys-benchmark/jobs/357887170
You can run the same benchmark using docker:
```
docker run --ulimit nofile=30000:30000 dmitrybalabka/aerys-benchmark:php71
```

**Comment by trowski** [comment]
Ignore the results using `amphp/cluster`, that was just for an example of what's possible. The first of my posts is comparing single processes only.

I should have looked closer at your v0.7.4 test file, I didn't realize you used `initServer`, but that actually didn't matter for the benchmark.

**v0.7.4:** Run using `php -dzend.assertions=-1 server-tiny.php`
```
Running 30s test @ http://localhost:8080/
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.91ms    4.67ms 258.70ms   99.46%
    Req/Sec    14.86k     1.26k   18.07k    71.33%
  Latency Distribution
     50%    6.48ms
     75%    7.32ms
     90%    8.07ms
     99%   10.48ms
  443601 requests in 30.00s, 87.57MB read
Requests/sec:  14784.99
Transfer/sec:      2.92MB
```
Nearly the same result as before.

So the real question is: **Why do I see similar performance between 0.7.4 and 0.8.0 on my laptop while travis and docker shows such a difference?**

I do not have an immediate answer to that question… in fact I got an even bigger performance gap running the docker you provided on my laptop. We clearly must have changed some default setting that is causing a huge performance penalty, but only on certain systems. I'm certain if we fix that setting the performance will be comparable to v0.7.4 on all systems.

**Comment by kelunik** [comment]
The HTTP server process isn't maxed out in that benchmark, but Aerys 0.7.x is on 100% CPU.

**Comment by trowski** [comment]
@torinaki Can you please update your benchmark to use v0.8.1? I'd like to try running the docker again.

**Comment by torinaki** [comment]
@kelunik, @trowski thanks you! Now it is back to normal. Comparing version v0.8.1 and v0.7.4 I've noticed only about 10% performance degradation.
Full report here: https://travis-ci.org/torinaki/aerys-benchmark/jobs/358118374

**Comment by torinaki** [comment]
@trowski image has been built. Please use:
```
docker run --ulimit nofile=30000:30000 dmitrybalabka/aerys-benchmark:php71
```

**Comment by kelunik** [comment]
Don't forget to run `docker pull dmitrybalabka/aerys-benchmark:php71` :)

**Comment by kelunik** [comment]
@torinaki `php -n` enables assertions. For improved performance, you should run with `-d zend.assertions=-1`.

**Comment by torinaki** [comment]
@kelunik I include all required settings in separate php.ini files like:
https://github.com/torinaki/aerys-benchmark/blob/a1272a7503fc4797d4711c6eaf93260611293d3b/php/default.ini#L1
and load it during each benchmark:
https://github.com/torinaki/aerys-benchmark/blob/aff9a11f62f3edc77f1ee230411f90ffb917a8a1/start_benchmark.sh#L62
I also check that it is really disabled, just to be sure that such approach works:
https://github.com/torinaki/aerys-benchmark/blob/aff9a11f62f3edc77f1ee230411f90ffb917a8a1/start_benchmark.sh#L50

**Comment by torinaki** [comment]
@trowski please hold on. Seems I have overridden the image with the old one. Please pull image again after build: https://travis-ci.org/torinaki/aerys-benchmark/builds/358158491
Sorry about this.
