### ISSUE TITLE
Logger performance decrease

### ISSUE THREAD

**Issue by cursedcoder** [amphp/http-server#256]
So I just ran some checks with simple `Hello World` using `autocannon` and `uv` loop.

Monolog with ConsoleFormatter logger:
```
Running 10s test @ http://localhost:3000
10 connections

Stat         Avg    Stdev   Max    
Latency (ms) 2.17   1.16    62.12  
Req/Sec      3924.9 251.81  4152   
Bytes/Sec    698 kB 48.2 kB 739 kB 

39k requests in 10s, 6.99 MB read
```

Monolog with SilentFormatter (don't print anything) logger:
```
Running 10s test @ http://localhost:3000
10 connections

Stat         Avg     Stdev   Max    
Latency (ms) 1.49    0.96    35.34  
Req/Sec      4733.61 252.79  5333   
Bytes/Sec    842 kB  43.5 kB 949 kB 

47k requests in 10s, 8.43 MB read
```

And then patched http-server with removed logger calls:
```
Running 10s test @ http://localhost:3000
10 connections

Stat         Avg     Stdev   Max     
Latency (ms) 1.23    0.83    36.53   
Req/Sec      5660.8  258.95  6382    
Bytes/Sec    1.01 MB 50.4 kB 1.14 MB 

57k requests in 10s, 10.1 MB read
```

In comparison to node `express`:
```
Running 10s test @ http://localhost:3000
10 connections

Stat         Avg     Stdev  Max    
Latency (ms) 1.1     0.83   34.59  
Req/Sec      6401.3  870.53 7400   
Bytes/Sec    1.38 MB 192 kB 1.6 MB 

64k requests in 10s, 13.8 MB read
```

Some code:
https://gist.github.com/cursedcoder/7758ed6c689e62976474435db988dabc

**Comment by kelunik** [comment]
So the take away is that logging takes CPU time? Anything I'm missing?

Debug logging is already covered inside `assert(... || true)` statements to have it zero-cost on production.

**Comment by cursedcoder** [comment]
Thanks for a tip, with proper log level it works like a charm!

```
$logHandler = new StreamHandler(new ResourceOutputStream(\STDOUT), \Psr\Log\LogLevel::ERROR);
```

**Comment by cursedcoder** [comment]
Just FYI, actually it does affect performance but not that much:

5400rps with logger
5700rps with patched logger

I believe various `assert` affect the performance anyway.

**Comment by kelunik** [comment]
If you have assertions disabled with `php -d zend.assertions=-1 script.php` there won't be any opcodes generated / executed by PHP, it's just entirely skipped.

**Comment by cursedcoder** [comment]
@kelunik wow, that's huge! 

now I get 7300+ rps
