### ISSUE TITLE
FastCGI driver implementation

### ISSUE THREAD

**Issue by torinaki** [amphp/http-server#259]
There is a [possibility](https://github.com/amphp/http-server/issues/61#issuecomment-381613466) to implement [FastCGI](https://en.wikipedia.org/wiki/FastCGI) as additional [HttpDriver](https://github.com/amphp/http-server/blob/32a3b0f97dc530179057fdcfad9b100efdca6c88/src/Driver/HttpDriver.php#L9).

According to protocol [specification](http://www.mit.edu/~yandros/doc/specs/fcgi-spec.html) and some implementations examples, it looks that protocol is quite simple.
Implementation examples:
1. https://github.com/PHPFastCGI/FastCGIDaemon/blob/master/src/Driver/Userland/ConnectionHandler/ConnectionHandler.php
2. https://github.com/hollodotme/fast-cgi-client
3. https://github.com/adoy/PHP-FastCGI-Client

FastCGI lighter than HTTP. I assume that application server can benefit from that if Nginx will be used as the reverse proxy.

**Comment by kelunik** [comment]
With the new architecture, this does no longer need to be some driver. This should be implemented as a separate package and just create a `Request` and call a corresponding `RequestHandler`.
