### ISSUE TITLE
Provide example for a Symfony app

### ISSUE THREAD

**Issue by mikemix** [amphp/http-server#263]
Especially how to convert your `Amp\Http\Server\Request` to Symfony's Request.

**Comment by kelunik** [comment]
A PR is welcome. ;-)

**Comment by mikemix** [comment]
If it was so easy. Not sure how to get the `_FILES` and the body as a string:

```
        $request = SymfonyRequest::create(
            $req->getUri()->getPath(),
            $req->getMethod(),
            [],
            $req->getCookies(),
            [],
            $_SERVER
        );
```

**Comment by torinaki** [comment]
@mikemix probably you might take a look on my repository where I'm experiencing to integrate Amp framework with Symfony (there is an example how to convert Amp request into Symfony request object):
https://github.com/torinaki/AmpBundle

The overall conclusion is the following. Currently, it is difficult to use Amp with Symfony. You have to override HttpKernel, because Controller should return generator to resolve the promise. This solves only the issue with the controller, but the same problem might appear with other Symfony components (e.g. Event Dispatcher)

IMO It would better wait with Amp with Symfony integration until PHP will have Fiber support (see https://github.com/fiberphp/fiber-ext, https://github.com/concurrent-php/ext-async)

If you are interested in a benchmark of Amp comparing with React and NodeJs you can take a look:
https://github.com/torinaki/aerys-benchmark

**Comment by mikemix** [comment]
I switched to Swoole. Thanks anyway.

**Comment by xcaptain** [comment]
I have a simple gist that can convert from amphp request to symfony request. with this convertion I can host lumen app using amphp server, juse replace the `public/index.php` file with [https://gist.github.com/xcaptain/d3184e2d5c75bea3c420c61872c37a69](https://gist.github.com/xcaptain/d3184e2d5c75bea3c420c61872c37a69)

**Comment by xcaptain** [comment]
@kelunik It's will be useful to provide a way to convert amphp request to symfony request, but currently it's hard to get `$_SERVER` and `$_FILES` from the request, can you provide some examples.

**Comment by kelunik** [comment]
Actually, it's impossible to fake `$_FILES` in a way that makes `move_uploaded_file` work, because PHP uses internal global variables for that that userland PHP doesn't have access to. So you'll need to change that in your framework of choice either way I guess.

**Comment by kelunik** [comment]
@xcaptain Just added a comment to your example. We probably have to rename `->read()` to `->readChunk()`, because it's a pretty common error I see. /cc @trowski

**Comment by bwoebi** [comment]
@xcaptain To get an array of `$_FILES`, you have to parse the content body e.g. via https://github.com/amphp/http-server-form-parser:

```php
$form = Amp\Http\Server\FormParser\parseForm($request);
$files = [];
foreach ($names as $name)
    foreach ($form->getFieldArray($name) as $fields) {
        foreach ($fields as $field) {
            $attributes = $field->getAttributes();
            if (!$attributes->isFile()) {
                continue;
            }
            $namePrefix = explode("[", $name)[0];
            $target = &$files[$namePrefix];
            if (preg_match_all('(\[\K[^\]]*(?=]))', $name, $m)) {
                foreach ($m[0] as $part) {
                    if ($part == "") {
                        $target[] = null;
                        end($target);
                        $part = key($target);
                    }
                    $target = &$target[$part];
                }
            }
            if (isset($target)) {
                continue;
            }

            # you may want to do something else here?!?
            $file_location = tempnam(ini_get("upload_tmp_dir"), "uploaded_file");
            file_put_contents($file_location, $field->getValue());

            $target["name"] = $attributes->getFilename();
            $target["type"] = $attributes->getMimeType();
            $target["size"] = strlen($field->getValue());
            $target["tmp_name"] = $file_location;
        }
    }
}
```

There is, however one problem: the `move_uploaded_files()` function does _not_ work if the file hasn't been added directly by a PHP SAPI. We cannot work around that from userland.

For `$_SERVER` you'll have to inspect `$request` as well as `$request->getClient()` and construct the array yourself from the available data.

**Comment by bwoebi** [comment]
@kelunik I agree on the rename, it's quite unexpected for newcomers - we consider everything with a read() being a stream and such returning chunks.

**Comment by xcaptain** [comment]
@bwoebi Thanks for the help about `$_FILES`, your example is a little out dated, I updated my example in https://gist.github.com/xcaptain/d3184e2d5c75bea3c420c61872c37a69#file-amphp_lumen-php-L72-L89
I can get `$_FILES` and then convert to symfony `UploadFile` type but still upload fail, the error says

```log
[2018-08-05 13:04:36] production.ERROR: Symfony\Component\HttpFoundation\File\Exception\FileException: The file "contract_state.png" was not uploaded due to an unknown error. in /home/joey/Projects/personal/lumen-amp/vendor/symfony/http-foundation/File/UploadedFile.php:239
Stack trace:
#0 /home/joey/Projects/personal/lumen-amp/app/Http/Controllers/BookController.php(27): Symfony\Component\HttpFoundation\File\UploadedFile->move('/tmp/a.png')
#1 [internal function]: App\Http\Controllers\BookController->upload(Object(Illuminate\Http\Request))
#2 /home/joey/Projects/personal/lumen-amp/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#3 /home/joey/Projects/personal/lumen-amp/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /home/joey/Projects/personal/lumen-amp/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(class@anonymous), Array, Object(Closure))
#5 /home/joey/Projects/personal/lumen-amp/vendor/illuminate/container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(class@anonymous), Array, Array, NULL)
#6 /home/joey/Projects/personal/lumen-amp/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(374): Illuminate\Container\Container->call(Array, Array)
```

My upload controller code is
```php
public function upload(Request $request)
{
    $file = $request->file('file1');
    $file->move('/tmp/a.png');
}
```
Is it the problem you said that `move_uploaded_files` cannot work around from userland?

**Comment by xcaptain** [comment]
I put my demo code [here](https://github.com/xcaptain/lumen-amp), this topic is interesting, once done we can serve lumen app using amphp http server

**Comment by bwoebi** [comment]
Yes, that's the problem, you'll have to extend the UploadedFile class and override that method, I guess.
