### ISSUE TITLE
how can i disable connection timeout?

### ISSUE THREAD

**Issue by eislambey** [amphp/http-server#273]
im trying to create a [sse](https://en.wikipedia.org/wiki/Server-sent_events) server. so i need keep connection alive. is there a way for disable timeout?

**Comment by kelunik** [comment]
Instead of doing that, I'd send newlines periodically. That way you can also detect broken connections and close them.

**Comment by kelunik** [comment]
Also, the timeout should only apply while the request is received from the client, not while the server is slow streaming the response, IIRC.

**Comment by eislambey** [comment]
after 15 seconds the connection is closing by server. i want to disable that.
https://github.com/amphp/http-server/blob/fc32336768886539eaac3ffaffb432b99c4c6837/src/Options.php#L10

**Comment by kelunik** [comment]
How does your request handler look like?

**Comment by eislambey** [comment]
like this
```php
$server = new Server($servers, new CallableRequestHandler(function (Request $request) {
    return new Response(Status::OK, [
        "content-type" => "text/event-stream; charset=utf-8",
        'Access-Control-Allow-Origin' => '*',
    ], new IteratorStream(new Producer(function (callable $emit){
        yield $emit(":ok\n\n");
        while(true){
            $rand = uniqid();
            yield $emit("data: $rand\n\n");
            yield new Delayed(1000);
        };
    })));
}), $logger, (new Options)->withoutCompression());
```

**Comment by bwoebi** [comment]
@kelunik The timeout always applies. It wasn't with Aerys, but now it does, we end up renewing the timeout each time we send a chunk of data:
https://github.com/amphp/http-server/blob/4c20c157eaa227169b5579cca7351fd1e922bd37/src/Driver/RemoteClient.php#L464

But sending something each second should work perfectly fine.

**Comment by kelunik** [comment]
@eislambey Thanks for the report. I've pushed a fix and will release a new version later today. You can try with `master` in the meantime.

@bwoebi I think that's another mistake in the implementation. The timeout shouldn't apply if there's nothing to send because the server takes longer to generate a response. We have `Client::isWaitingForResponse()` for that exact purpose, but apparently we don't use it. /cc @trowski

**Comment by trowski** [comment]
@kelunik I think `Client::isWaitingForResponse()` was suppose to be used in `Server::timeoutKeepAlives()`, but was overlooked.

**Comment by kelunik** [comment]
@trowski Just pushed a commit that fixes that.
