### ISSUE TITLE
Why direct sockets used instead of SocketServer ?

### ISSUE THREAD

**Issue by Ekstazi** [amphp/http-server#278]
https://github.com/amphp/http-server/blob/a7aeae87da84333bd4d86e4bc67356fcc261c189/src/Server.php#L104

https://github.com/amphp/http-server/blob/a7aeae87da84333bd4d86e4bc67356fcc261c189/src/Server.php#L309

https://github.com/amphp/http-server/blob/a7aeae87da84333bd4d86e4bc67356fcc261c189/src/Server.php#L318

https://github.com/amphp/http-server/blob/a7aeae87da84333bd4d86e4bc67356fcc261c189/src/Server.php#L331

SocketServer support tls and accept methods. So why http server use rar sockets instead of abstractions ?

**Comment by bwoebi** [comment]
This was afaik done for performance reasons, in particular all incoming client connections are (nearly) permanently alive and we just disable watching when our internal buffer limit gets reached.

It's in the end a lot of objects and enabling back and forth (if you consider ResourceInputStream->read() for example).
And this is in the hot path of the server...

**Comment by kelunik** [comment]
It seems like all questions have been answered. If not, please respond with further questions, the issue can always be re-opened. :+1:
