### ISSUE TITLE
Concatenate error when trying to train a two input one output network 

### ISSUE THREAD

**Issue by 47euewxm** [amphp/http-server#280]
Hi,
I'm trying to train a 2 input one output model using the Keras API. The model seems to be right and all but at the end when I try to train it shows an error when it tries to concatenate the two outputs of the branches. It says that a two-dimensional array is expected and it gets a (x,y,z) input.
Being 'x' my batch size and 'y' and 'z' the size of the image. I have already tried using a batch size of 1 and the same error happens.[毕业真实版本=|彼得学院毕业证书-|剑桥大学真实原件文凭证书=英国文凭办理‖国外文凭办理→国外学历学位认证](www.diplomaclub.net) 
I have also tried using add instead of concatenating but the same error shows.

**Comment by kelunik** [comment]
Not sur ehow
