### ISSUE TITLE
withConnectionTimeout isn't available

### ISSUE THREAD

**Issue by dbalabka** [amphp/http-server#293]
Seems following option isn't available any more:
https://github.com/amphp/http-server/blob/master/docs/classes/options.md#withconnectiontimeoutint-seconds-options

Related commits: 
1. https://github.com/amphp/http-server/commit/84b8b5e58cad339c4c70f95a8107fa5a5dac0e05#diff-eaf8868b994390699bd8b3db948d8aaf
2. https://github.com/amphp/http-server/commit/1e8679f8ee8201109a6f1e0e6324bf0b7e9cb4f9#diff-eaf8868b994390699bd8b3db948d8aaf

**Comment by trowski** [comment]
Looks like we have some more documentation updates to make before a final 2.0 tag.

**Comment by ykdui** [comment]
Hello, cybercrooks!

Would you like to buy dumps and credit cards with cvv2 from the legendary Brian Krebs? In my shop you will find fresh firsthand dumps & cards at a great price!

What you can buy:
Dumps with Track 1 & Track 2 and billing zip code
Сredit Cards with CVV2
Social Security Numbers and Date of Birth lookups
Why buy from Brian Krebs?
Auction that allows you to reserve, bid and outbid others who want to purchase exotic BINs
Free gift/dump for everyday shoppers
Social Security Number & Date of Birth lookup service to change PIN or approve large transactions for the dumps & cards you buy
Dumps with billing zip codes
Lottery where anyone can win large amount of money
3 crab rating is fixed for old school and high deposit customers
Fully automated loan/credit request system

all other domains are a scam! No sales in ICQ, Jabber, Telegram.
Payment methods:
Bitcoin

Terms & Conditions as well as replacement policy are available on the website for registered users. Registration is free.

Regular daily updates 7 times a week. Plus you can grab the most exotic bins in the Auction. Bid on the rare 101 bins and outbid others to grab them!

Good luck with your bin choices! Stay safe & healthy!
Who need PayPal Or WU Transfer Cash App
5$ For  50$ 

10$ For 100$

20$ For 200$

30$ For 300$

40$ For 400$ 

50$ For 500$

60$ For 600$

70$ For 700$ 

80$ For 800$

No rippers allowed to pm me. 
Let all eat together 
PM ME Now For Your Own 
 ICQ ...... calrity.baron@bk.ru

 ICQ ...... calrity.baron@bk.ru

TeleGram.....@Ykidven

TeleGram.....@Ykidven

**Comment by trowski** [comment]
Updated the docs some time ago, forgot about closing this.
