### ISSUE TITLE
Documentation version

### ISSUE THREAD

**Issue by enumag** [amphp/http-server#296]
I want to try out this package. For compatibility with the rest of my stack I need to use the 2.0-RC version. I'm wondering if the documentation at https://amphp.org/http-server/ is for 1.1 or 2.0. And if it is for stable 1.1 then is there an updated version of the documentation somewhere?

Thanks!

**Comment by kelunik** [comment]
It's always what's contained in the `master` branch in the `./docs` directory. It's mainly for 1.1, as we haven't updated much for 2.x, yet, I think.

**Comment by enumag** [comment]
I see. Ok, I'll be careful about possible differences when using 2.0. Thanks.

**Comment by trowski** [comment]
@enumag Skim through the [2.0 RC release notes](https://github.com/amphp/http-server/releases) for a quick summary of changes. There's a good amount of changes, but few (if any) touch the request/response stack, so most of the docs still apply and most user code for 1.x should work fine with 2.0.
