### ISSUE TITLE
How to handle security?

### ISSUE THREAD

**Issue by enumag** [amphp/http-server#301]
Is there some library to handle authentication and authorization in async environment? If not, can you give me some tips how you do it?

I've been using symfony/security previously, but it is request-response oriented (the current authentication token is saved in a global stateful service) so I can't use it with Amphp.

Thanks for any advice.

Note: I do know about https://github.com/amphp/http-server-session. I mean something on top of that to help me handle authentication / authorization. Also I'm actually building an API though so I don't really need session - using an authentication header instead.

**Comment by kelunik** [comment]
Authentication / authorization should probably not be tied to HTTP as transport. You'll probably have a `User` object of some kind. If you want to have role based access controls, you'd for example have a `getRoles(): string[]` method on the user object to check the roles corresponding to the user or something like `hasRole(string): boolean`.

Then you could use something like the following in your request handler:

```php
$user = $this->getLoggedInUser();

if ($user === null || !$user->hasRole('some-role')) {
    return $this->error("Access denied");
}
```

`getLoggedInUser()` could be defined in a parent class of your request handlers.

**Comment by enumag** [comment]
I did some research how security works in Symfony. Authentication in Symfony is very sophisticated but ultimately I don't need anything from that so I'll implement some simple token verification in my request handlers. For Authorization I just need to change Voters to be able to return promises and then pretty much copy-paste the [affirmative strategy](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authorization/AccessDecisionManager.php#L69-L95) from Symfony.
