### ISSUE TITLE
CorsMiddleware

### ISSUE THREAD

**Issue by enumag** [amphp/http-server#303]
I need to handle CORS headers in my application so I kinda need a CorsMiddleware to add the necessary headers.

I found an implementation [here](https://github.com/labrador-kennel/http-cors/blob/master/src/CorsMiddleware.php) but the package doesn't allow `amphp/http-server` 2.0 and the organization seems inactive since November 2019. I'm not really interested in forking and maintaining it so I have two choices:

- Copy it to my own application
- Refactor and contribute it to amphp/http-server directly

Other ppl might need it as well I think. Depends on if you want to have such middleware here and maintain it or prefer to keep your package light-weight and have the community take care of it on their own.

**Comment by kelunik** [comment]
Seems like there's already a good library you linked. How about opening a PR there to add 2.0 compatibility?

**Comment by enumag** [comment]
I already offered to do that [here](https://github.com/labrador-kennel/http-cors/pull/1#issuecomment-585661662) but the author isn't replying and overall the entire organization nor the author have any recent activity on GitHub.

**Comment by enumag** [comment]
bump

**Comment by kelunik** [comment]
I've tried to ping the author on Stackoverflow chat, but didn't get any response.

**Comment by enumag** [comment]
Yeah... so which way do you want me to go? Do you want such middleware in this package or not?

**Comment by kelunik** [comment]
I'd say it should be its own package, just like the router, session and static-content plug-ins are their own packages. I don't have a strong opinion whether it should be under the @amphp namespace or not.

**Comment by enumag** [comment]
The author just replied saying that he should be more available now. I'll send a PR to the linked repo.

**Comment by kelunik** [comment]
@enumag Please send a PR to include a link into the README and/or documentation here.

**Comment by enumag** [comment]
I will once there is a release compatible with latest amphp. ;-)

**Comment by kelunik** [comment]
@enumag Thanks, meant to say exactly that!
