### ISSUE TITLE
Save array to cookie

### ISSUE THREAD

**Issue by prolic** [amphp/http-server#307]
How can a save a php array to a cookie? Using "serialize" or "json_encode" I receive a `InvalidCookieException`.

Is there a simple way to do this?

``` 
// set the cookies
setcookie("cookie[three]", "cookiethree");
setcookie("cookie[two]", "cookietwo");
setcookie("cookie[one]", "cookieone");

// after the page reloads, print them out
if (isset($_COOKIE['cookie'])) {
    foreach ($_COOKIE['cookie'] as $name => $value) {
        $name = htmlspecialchars($name);
        $value = htmlspecialchars($value);
        echo "$name : $value <br />\n";
    }
}
```

Currently I don't know what the cookie name is, because it's part of my lib. So I cannot do it manually (at least not very easy).

**Comment by kelunik** [comment]
I'd use json_encode + base64. I'm not sure whether the code you posted sets one or three cookies, my guess would be three.

**Comment by prolic** [comment]
> I'd use json_encode + base64.

Of course, why haven't I thought of it myself.
