### ISSUE TITLE
Question: Request POST data?

### ISSUE THREAD

**Issue by enumag** [amphp/http-server#311]
Looking at the [Request](https://amphp.org/http-server/classes/request) and [RequestBody](https://amphp.org/http-server/classes/request-body) API I'm not sure how to get POST parameters and uploaded files from the request. Can you give me some example please?

**Comment by kelunik** [comment]
https://github.com/amphp/http-server-form-parser can be used for that.

**Comment by enumag** [comment]
I see. I can't find it mentioned in the readme or documentation of `amphp/http-server` at all. I'll try to send a PR to add it there.
