### ISSUE TITLE
Call to a member function on null

### ISSUE THREAD

**Issue by bileslaw** [amphp/http-server#336]
I unfortunately lost the logged exception in my buggy clipboard, but here's the gist: `$reason` on [this line](https://github.com/amphp/http-server/blob/3f24c16e00dfba7f2a553128ff1ae7e92fd85952/src/Driver/Http2Driver.php#L394) may be null under some circumstances. This will crash the server, as happened to me.

**Comment by trowski** [comment]
Fixed via https://github.com/amphp/http-server/commit/fef588a3e3eff4c524d62f7b7b0673f5a1c71579. Thanks for reporting!
