### ISSUE TITLE
Brotli compression in addition to gzip

### ISSUE THREAD

**Issue by attisan** [amphp/http-server#337]
Brotli provides significantly smaller payload sizes and thus would / could further improve response speed. Could be integrated optionally in case https://github.com/kjdev/php-ext-brotli is detected?

**Comment by kelunik** [comment]
Sounds like a good addition, so you want to provide a small PR?

**Comment by attisan** [comment]
I'm on it. Should I Add it to CompressionMiddleware or stack a new BrotliCompressionMiddleware in in case Brotli is available? Doing the latter would keep the CompressionMiddleware a bit more readable as we need to use brotli_compress_init instead of deflate_init (and friends).

**Comment by trowski** [comment]
I think it makes sense to roll support into `CompressionMiddleware`. You'll probably want to split out deflate and brotli into separate handler methods and defer to them to keep it clean and readable.

**Comment by attisan** [comment]
should there be a setting indicating if Brotli should be used? I'm undecided on whether Brotli should outweigh gzip if it is available on the server as it does slow down the response.

**Comment by kelunik** [comment]
I'm closing this. If the mentioned overhead is true, this won't be beneficial for application server requests. Static resources should usually be served by a load balancer / CDN in front, not by the application server directly.
