### ISSUE TITLE
Example in README.md is outdated

### ISSUE THREAD

**Issue by AntonioNav** [amphp/http-server#346]
I'm trying to run a simple test with this libray, but I'm unable to find up to date documentation, even the example in the README.md file is outdated and don't work with all the changes to use Revolt. The link to the "Official Documentation" (http://amphp.org/http-server/) is also broken.

I would appreciate if someone could guide me where to find documentation or examples using Revolt and Amphp to set up an http server.

**Comment by kelunik** [comment]
You can find updated examples for the upcoming version in the `examples` directory. If you're looking for the current stable version, have a look here: https://github.com/amphp/http-server/tree/2.x/docs

Docs on amphp.org for this package are indeed currently broken. We're working on a major update for the documentation and this package hasn't been migrated, yet.

**Comment by AntonioNav** [comment]
Thank you for your response.

I'm sorry for not seen the directory of examples. On the other hand, if the default branch of the repository is 3.x, I think it would be appropriate to modify the Readme.md example to match that version.
