### ISSUE TITLE
HTTP3 support

### ISSUE THREAD

**Issue by raghuveer** [amphp/http-server#359]
Hi

Any plans to support HTTP3 with integration of nghttp3 library in amphp HTTP server in future? 

Alternatively, can Amphp HTTP server be deployed behind Nginx (Nginx being HTTP3 compliant in recent time) and by using Nginx as reverse proxy before amphp http server?

Please share your inputs

Thank you

**Comment by kelunik** [comment]
There aren't any plans to support http3 in the near future, but you can of course deploy something like nginx in front to support http3.

**Comment by raghuveer** [comment]
thanks for the confirmation about possible options
