### ISSUE TITLE
Potential socket wait on timeout if the server wants to terminate.

### ISSUE THREAD

**Issue by EdmondDantes** [amphp/http-server#370]
I don't know if this situation is correct or not, but the server will wait for the socket during termination, even if no packets are being sent through this socket. This leads to prolonged termination.

It is recommended to add operation cancellation upon termination event.

https://github.com/amphp/http-server/blob/26001b1ffac11db30c627ed4daba2088951b0ffa/src/Driver/Http1Driver.php#L144

**Comment by trowski** [comment]
Updated the driver to cancel reading a request upon shutdown. Thanks for pointing out this issue! 👍
