### ISSUE TITLE
Method League\Uri\Http::createFromComponents() is deprecated

### ISSUE THREAD

**Issue by lav45** [amphp/http-server#376]
```
Method League\Uri\Http::createFromComponents() is deprecated since league/uri:7.0.0, use League\Uri\Http::fromComponents()
```

- vendor/amphp/http-server/src/Driver/Http1Driver.php
- vendor/amphp/http-server/src/Driver/Http2Driver.php

**Comment by bwoebi** [comment]
@trowski I'm confused. Did you somehow just drop the deprecations lines for the code in the HttpDrivers? The deprecation message is still present.
